# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 85af9f45b317cd525c044a0ff5d3742b3b739f4b3de6e63e2d1a28f836d2a6eaa3b70c01098cb3df39c9310974a1a8ac944464a140c56d43d7426e4b96c04854

test:
  secret_key_base: 7a164673d859f80da40e0bba49eb9fa5faaa7895cdbab894d3990f26bb18cb1e7039ea71eda4bf98f8c4b4be539b97ab540b0bd5a53238251057fff152e9427b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
